### ISSUE TITLE
Cant run...

### ISSUE THREAD

**Issue by ghost** [Allu2/TeeBot2#2]
Cant run bot on my VPS. Python 3.4.3, Ubuntu 14.
I try to connect it to DDNet 9.2 server.
$ python3 Bot.py

DEBUG:Bot:Connecting to server..
Exception in thread Ene:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/user/TeeBot2/TeeBot.py", line 260, in run
    self.tn  = self.connect
  File "/home/user/TeeBot2/TeeBot.py", line 78, in connect
    self.tn = telnetlib.Telnet(self.host, self.port)
  File "/usr/lib/python3.4/telnetlib.py", line 221, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.4/telnetlib.py", line 237, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Any ideas? :anguished:

**Comment by Allu2** [comment]
Last time I checked DDNet server didn't support the Econ (Telnet) remote connection to rcon that Vanilla server does. TeeBot needs this to work.
